### ISSUE TITLE
Terminal spams 'request settings' when disconnected from MCU

### ISSUE THREAD

**Issue by pietertolsma** [OperationAIR/HumanInterface#22]

**Comment by Verzijl** [comment]
Nu master in mijn branch gemerged en nu heb ik dit ook.
Gebeurd in viewController.py
Misschien een kleine check toevoegen voor wanneer in dev mode

**Comment by ijager** [comment]
oh ja, dat moet ie niet doen als `SIMULATE=True`

**Comment by ijager** [comment]
Gefixt in master
