### ISSUE TITLE
Begin-pagina om tijd in te stellen

### ISSUE THREAD

**Issue by ijager** [OperationAIR/HumanInterface#9]
Even kijken wat hier de beste manier voor is. Wellicht een popup in aan het eind van app.__init__ ?
Of wordt het een TK app die uitgevoerd wordt vóór dat de standaard app gestart wordt. 

Er moet denk ik ook een manier komen om de tijd aan te passen terwijl de app al bezig is.

**Comment by ijager** [comment]
Misschien ook maar de datum instellen, hoe gaan we dat anders doen met logs van meerdere dagen?

**Comment by pietertolsma** [comment]
Idee: loggen met relatieve tijd. Bij systemcrash in principe nieuw logbestand beginnen (Of beginnen waar ge eindigd).

Tijd kan ingesteld worden, alleen zie ik niet voor me hoe een jaar maand en dag er bij ook nog praktisch is

**Comment by JeffreyVisser1** [comment]
begin scherm is er.
